const BAD_REQUEST_ERROR = 400;
const UNAUTHORIZED = 401;
const FORBIDDEN_ERROR = 403;
const NOTFOUND_ERROR = 404;
const CONFLICT_ERROR = 409;
const DEFAULT_ERROR = 500;

module.exports = {
  BAD_REQUEST_ERROR,
  UNAUTHORIZED,
  FORBIDDEN_ERROR,
  NOTFOUND_ERROR,
  CONFLICT_ERROR,
  DEFAULT_ERROR,
};
